config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:index, :show, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :replies, only: [:index, :new, :create] #At the end we don't need index for replies
  resources :categories, only: [:index, :show, :new, :create, :destroy]
  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] #No need for index for posts
  resources :comments, only: [:new, :show, :create, :edit, :update, :destroy]


  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#logout'
  get '/about' => 'sessions#about' #This will be the homepage/about page... will display options to log in or signup

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts

    validates :name, presence: true
    validates :description, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post

    #big brain plays below
    belongs_to :parent, class_name: "Comment", optional: true

    has_many :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy

    validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :category
    has_many :comments, dependent: :destroy

    # validates :user_id, presence: true
    # validates :category_id, presence: true
    validates :content, presence: true
    validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy

    validates :full_name, presence: true, uniqueness: true
    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true

    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user
    helper_method :current_post
    helper_method :categories

    def current_user
        # memoization
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
        return @current_user
    end

    def current_post
        if session[:post_id]
            @current_post ||= Post.find(session[:post_id])
        end
        return @current_post
    end

    def logged_in?
        !!current_user #one bang converts into boolean...
    end

    def admin
        flash[:alert] = "Only Admins have that capability!"
        redirect_to login_path unless current_user.admin
    end

    def authorized
        flash[:login_warning] = "You must be logged in to use that function"
        redirect_to login_path unless logged_in?
    end

    def categories 
        arr = []
        Category.all.each do |category|
            arr << category
        end
        return arr
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :authorized, only: [:new, :create, :edit, :update]

  def index
    @categories = Category.all
  end

  #implement a like system? or sort by new?
  def show
    @category = Category.find(params[:id])
    @post = @category.posts
  end

  def new
    @category = Category.new
  end

  #haven't tested this out yet... delete comment if it works
  def create
    @category = Category.new(category_params)
    if @category.valid?
      @category.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  private
  def category_params
    params.require(:category).permit(:name, :description)
  end
end


# def new
#   @user = User.new
# end

# def create
#   @user = User.new(user_params)
#   if @user.valid?
#     @user.save
#     redirect_to user_path(@user)
#   else
#     render :new  
#   end
# end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authorized, only: [:new, :create, :edit, :update]
  before_action :current_user, only: [:destroy]
  
  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
    @post = params[:post]
    if params[:parent_id]
      @parent_id = params[:parent_id]
    end
  end 

  def create
    @comment = Comment.new(comment_params)
    if @comment.valid?
       @comment.save
       redirect_to post_path(@comment.post)
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @post = params[:post]
    if params[:parent_id]
      @parent_id = params[:parent_id]
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to post_path(@comment.post)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@comment.post)
  end

  private
  def comment_params
    params.require(:comment).permit(:post_id, :user_id, :content, :parent_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authorized, only: [:new, :create, :edit, :update]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    current_user
    @post = Post.new

    if params[:category_id]
      @category_id = params[:category_id]
      @category_name = params[:category_name]
    end


  end

  # params we are getting  {"category" => int, "user" => int, ... } 
  #           needs to be {"category_id" => int, "user_id" => int...}
  # Can't find way to change post params :category, :user keys with '_id' after without
  # it breaking... ask Monday.
  def create
    # @post = Post.new(category_id: params[:post][:category],
    #                  user_id: params[:post][:user],
    #                  content: params[:post][:content],
    #                  title: params[:post][:title])
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.valid?
       @post.save
       redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

  end

  #not using this for now... save this tho.
  def post_params
    params.require(:post).permit(:category_id, :user_id, :content, :title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to user_path(user)
    else 
      redirect_to login_path, notice: "User not found with those credentials"
    end

  end

  def logout
    session.clear
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.admin = false
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  #make sure to implement unique username, email, full_name validations
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:full_name, :email, :username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<div class="category_page">
<h1>All The Categories</h1>
<ul>
<% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
<%end %>
</ul>

<%= link_to "Create a New Category", new_category_path %>
</div>

app/views/categories/new.html.erb
<div class="new_category">
<h1>Create a New Category</h1>
<%= form_for @category do |c| %>
	<%= c.label :name %>
	<%= c.text_field :name %> 
	<br>
	<br>
	<%= c.label :description %>
	<%= c.text_area :description%>
	<br>
	<br>
	<%= c.submit %>
	<% end %>

</div>

app/views/categories/show.html.erb
<div class="category_show_page">
    <div class="category_desc">
        <br/>
        <h1><%=@category.name%></h1>
        <h3><%=@category.description%></h3>
        <br>
        <p><%= link_to "Create New Post", new_post_path(category_name: @category.name, category_id: @category.id) %></p>
        <br>
        <br>
    </div>
    <hr/>
    <h3 class="post_show_heading">Posts</h3>
    <br>
    <div class="div_holding_all_posts">
        <% @category.posts.each do |post| %>
                <div class="post_card">
                    <h3 class="categ_show_post_title">
                        <%= link_to post.title, post_path(post) %>
                    </h3>
                    <hr class="make_horizontal_line_smaller"/>
                    <em class="posted_by_spacing">
                        Posted by: 
                        <b>
                        <%= post.user.username %>
                        </b>
                    </em>
                    <br>
                </div>
        <% end %>
    </div>
    <br>
    <br>
    <%= link_to "Categories Homepage", categories_path %>
</div>

app/views/comments/edit.html.erb
<h1>Edit this Comment</h1>

<%=form_for @comment do |p| %>
	<br>
	<%= p.label :content %></b>
	<%= p.text_field :content%>
	<br>
	<%= p.submit %>
<% end %>

app/views/comments/index.html.erb
<h1>Comments:</h1>

app/views/comments/new.html.erb
<div class="new_comment">
<h1>New Comment</h1>

<% if @comment.errors.any? %>
    <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
<% end %>

<%=form_for @comment do |p| %>
	<br>
	<!--<b><%= p.label :users %><b>
	<%= p.collection_select :user_id, User.all, :id, :username, prompt: true %>
	<br>
	-->
    <%= hidden_field(:comment, :parent_id, :value => @parent_id) %>
    <%= hidden_field(:comment, :post_id, :value => @post) %>
    <%= hidden_field(:comment, :user_id, :value => current_user.id) %>
	<br>
	<b><%= p.label :content %></b>
	<%= p.text_field :content%>
	<br>
	<%= p.submit %>
<% end %>
</div>

app/views/comments/show.html.erb
<h1><%= @comment.user.username %> comment </h1>
<p> <%=@comment.content %>
<br>
<%= button_to "delete", @comment, :method => "delete" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="navigation">
      <div class="logo">
        <span><%= link_to "Askit", about_path %>
      </div>
      <div class="ui animated fade button biggerButton home" tabindex="0">
        <div class="visible content">
          <p class="nav_bar_text_align">Users</p>
        </div>
        <div class="hidden content">
          <span><%= link_to "Users Index", users_path%>
        </div>
      </div>
      <div class="ui animated fade button biggerButton home" tabindex="0">
        <div class="visible content">
          <p class="categories_wrap_it_up">Categ</p>
        </div>
        <div class="hidden content">
          <%= link_to categories_path do %>
          <p class="categories_hover">Categories</p>
          <% end %>
        </div>
      </div>
      <% if session[:user_id] %>
      <div class="ui animated fade button biggerButton home" tabindex="0">
        <div class="visible content">
          <p class="nav_bar_text_align2">Profile</p>
        </div>
        <div class="hidden content">
          <span><%= link_to "Your Page", user_path(current_user) %>
        </div>
      </div>
      <div class="ui animated fade button biggerButton home" tabindex="0">
        <div class="visible content">
          <p class="nav_bar_text_align2">Logout</p>
        </div>
        <div class="hidden content">
          <span><%= link_to "Exit", "/logout" %>
        </div>
      </div>
      <div class="home login_status">
        <h4>Logged in as: <%= current_user.username %></h4>
        <% if current_user.admin == true %>
          <h5 class="red nav_logged_in"><b>ADMIN</b></h5>
        <% end %>
      </div>
    </div> <!--Navigation class ends here for if statement -->

    <% else %> <!--If the session[:user_id] is nil -->

      <div class="ui animated fade button biggerButton home" tabindex="0">
        <div class="visible content"><i class="user plus icon icon_alignment_nav_bar"></i>
        </div>
        <div class="hidden content">
          <span><%= link_to "Create Account", new_user_path %>
        </div>
      </div>
      <div class="ui animated fade button biggerButton home" tabindex="0">
        <div class="visible content">
          <p class="nav_bar_text_align">Login</p>
        </div>
        <div class="hidden content">
          <span><%= link_to "Sign In", login_path %>
        </div>
      </div>
      <div class="home login_status">
        <h4>You are currently not logged in.
          <br>
          <%= link_to "Create an account", new_user_path %> or <%= link_to "Login", login_path %>
          <br>
          To get the most out of this app.
        </h4>
      </div>
    </div> <!-- Navigation class ends here for else statement -->
    <% end %>
  <div class="container_excluding_nav_bar"><!-- If i do this I need to maybe add a </div> to the end of every html...-->
  <!-- It is set up so that the nav Bar won't display that transition... only the content-->
  <br>
  <br>
  
  <%= yield %>
  </div>
  </body>
</html>

app/views/posts/edit.html.erb
<h1> Edit Page: <%= @post.title%> </h1>

<%=form_for @post do |p| %>
	<br>
	<!--<b><%= p.label :users %><b>
	<%= p.collection_select :user_id, User.all, :id, :username, prompt: true %>
	<br>
	-->
	<b><%= p.label :categories %></b>
	<%= p.collection_select :category_id, Category.all, :id, :name, prompt: true %>
	<br>
	<br>
	<b><%= p.label :title %></b>
	<%= p.text_field :title %>
	<br>
	<br>
	<b><%= p.label :content %></b>
	<br>
	<%= p.text_area :content%>
	<br>
	<%= p.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>Post Page</h1>
<ul>
<% @posts.each do |post| %>
    <li><%= link_to post.content, post_path(post) %></li><br>
<% end %>
</ul>  

app/views/posts/new.html.erb
<div class="category_post_new">
<%if @category_id && @category_name %> <!-- If user clicked New Post from a specific Category Page -->
	<h1>New Post For <%= @category_name%></h1>
<% else %>
	<h1>Create A New Post</h1>
<% end %>

<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
<% end %>

<%=form_for @post do |p| %>
	<br>
	<!--<b><%= p.label :users %><b>
	<%= p.collection_select :user_id, User.all, :id, :username, prompt: true %>
	<br>
	-->
	<%if @category_id && @category_name %> <!-- If user clicked New Post from a specific Category Page -->
		<%= hidden_field(:post, :category_id, :value => @category_id) %>
	<% else %> <!-- When User selects New Post on their profile page -->
		<b><%= p.label :categories %></b>
		<%= p.collection_select :category_id, Category.all, :id, :name, prompt: true %>
	<% end %>
	<br>
	<br>
	<b><%= p.label :title %></b>
	<%= p.text_field :title %>
	<br>
	<br>
	<b><%= p.label :content %></b>
	<%= p.text_field :content%>
	<br>
	<%= p.submit %>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="category_post_content">
    <h1>Category: <%= @post.category.name %></h1>
    <br>
    <h2><%=@post.title%></h2>

    <h3>Posted By: <%= @post.user.username %></h3>
    <% if current_user != nil %> <!-- Need this here because it will break if Logged in as visitor... doesn't know what nil.admin is -->
        <% if session[:user_id] == @post.user_id %>
            <%= link_to edit_post_path(@post) do %>
                <button class="ui button"><i class="edit icon">Edit</i></button>
            <% end %>
        <% end %>
        <% if session[:user_id] == @post.user_id || current_user.admin %>
        <%= link_to post_path(@post), method: :delete do %>
            <button class="ui button"><i class="trash icon">Delete</i></button>
        <% end %>
        <% end %>
    <% end %>
    <br>
    <p><%=@post.content%></p>
    <p><%= link_to "Comment to Post", new_comment_path(post: @post.id) %>

</div> <!--End of Category_post_content div class -->


<div class="comment_header_alignment"><h4>Comments</h4>
<% @post.comments.each do |comment| %>
    <% if comment.parent_id == nil %> <!-- If this comment is parent... prevents replies displaying themselves as parent comment -->
        <div id="parent_comment_container">
        <li><b><%=comment.user.username %>:</b> 
        <%= link_to new_comment_path(parent_id: comment.id, post: @post.id) do %>
            <button class="ui button"><i class="reply icon">Reply</i></button>
        <% end %>
        <% if current_user != nil %>
            <% if session[:user_id] == comment.user_id%>
                <%= link_to edit_comment_path(comment) do %>
                    <button class="ui button"><i class="edit icon">Edit</i></button>
                <% end %>
            <% end %>
            <% if session[:user_id] == comment.user_id || current_user.admin %>
            <%= link_to comment_path(comment), method: :delete do %>
                <button class="ui button"><i class="trash icon">Delete</i></button>
                <% end %>
            <% end %>
        <% end %>
        <br>
        <%=comment.content%>
        </li>
        </div>
        <% if comment.replies %>
        <div class="reply_list_div">
            <ul>
            <% comment.replies.each do |reply| %>
                <li class="li_width_100"><b><%=reply.user.username%>:</b>
                <% if current_user != nil %>
                    <% if session[:user_id] == reply.user_id%>
                        <%= link_to edit_comment_path(reply) do %>
                        <button class="ui button"><i class="edit icon">Edit</i></button>
                        <% end %>
                    <% end %>
                    <% if session[:user_id] == reply.user_id || current_user.admin %>
                        <%= link_to comment_path(reply), method: :delete do %>
                        <button class="ui button"><i class="trash icon">Delete</i></button>
                        <% end %>
                    <%end%>
                 <%end%>
                 <br>
                 <%=reply.content%>
                </li>
                <br>
            <%end%>
            </ul>
        </div>
        <% end %> <!-- End of if comment.replies>
        <br>
    <% end %>
<% end %> <!--End of Post.comments.each do iteration -->
</div>
<br>
<br>
<br>

app/views/replies/edit.html.erb
<h1>Replies#edit</h1>
<p>Find me in app/views/replies/edit.html.erb</p>

app/views/replies/index.html.erb
<h1>All Replies</h1>

<ul>
<% @replies.each do |reply| %>
    <li><%= reply.content %></li>
<% end %>
</ul>

app/views/replies/new.html.erb
<h1>Replies#new</h1>
<p>Find me in app/views/replies/new.html.erb</p>

app/views/replies/show.html.erb
<h1>Replies#show</h1>
<p>Find me in app/views/replies/show.html.erb</p>

app/views/users/edit.html.erb
<h1><%= @user.username %> edit form</h1>
<br>
<br>
<%= form_for @user do |f| %>
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
    <br>
    <br>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <%= f.submit %>
<% end %>

<%link_to "Users Page", users_path %>

app/views/users/index.html.erb
<div class="user_index_page">
<h1>All The Users</h1>

<ul>
<% @users.each do |user| %>
    <li><%=link_to user.full_name, user_path(user)%></li>
<% end %>
</ul>
<br>
<br>
<%= link_to "Create New User", new_user_path %>
</div>

app/views/users/new.html.erb
<div id="new_user_container">
<h1 class="center_h1_new">New User Form</h1>
<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
<% end %>

<br>

<%= form_for @user do |f| %>
	<div id="center_form_in_container">
	<div class="center_full_name">
	<b><%= f.label :full_name%>:</b>
	<%= f.text_field :full_name%>
	<br>
	</div>
	<div class="center_username">
	<b><%= f.label :username%>:</b>
	<%= f.text_field :username%>
	<br>
	</div>
	<div class="center_email">
	<b><%= f.label :email%>:</b>
	<%= f.text_field :email%>
	<br>
	</div>
	<div class="center_password">
	<b><%= f.label :password %>:</b>
	<%= f.password_field :password%>
	<br>
	</div>
	<div class="center_password_confirmation">
	<b><%= f.label :password_confirmation %>:</b>
	<%= f.password_field :password_confirmation %>
	<br>
	</div>
	<br>
	<div class="center_submit">
	<b><%= f.submit %></b>
	</div>
	<br>
	</div>
<% end %>


<br>
<br>
<%= link_to "Cancel", users_path %>
</div>

app/views/users/show.html.erb
<!-- There is probably a better way to do the below, in regards to 
the usage of the if else conditionals checking if a user is logged in-->

<div class="user_home_overall">
<h1 class="center_h1_user_homepage">
<%if session[:user_id] == @user.id%>
	Your Homepage
<%else %>
	<%=@user.username%> Homepage
<% end %>
</h1>

<div class="make_smaller_h4_padding">
<h4 class="center_name_h4">Name: <%= @user.full_name %></h4>
<h4 class="center_email_h4">Email: <%= @user.email %></h4>
</div>

<div class="center_user_links">
<% if session[:user_id] == @user.id%>
<%= link_to "Edit Profile", edit_user_path(@user)%>
<br>
<br>
<%= link_to "Create a New Post", new_post_path %>
<% end %>
</div>

<div id="user_posts">
<%if session[:user_id] == @user.id %>
	<h1>Your Post(s)</h1>
	<% if @user.posts.count == 0 %>
		<h2>Looks like you haven't posted anything yet :(</h2>
		<br><p><%= link_to "Create a New Post!", new_post_path %></p>
	<% else %>
	<ul>
	<% @user.posts.each do |p| %>
		<li>Category: <%= link_to p.category.name, category_path(p.category) %>
			<br>
			<p>Title: <%= link_to p.title, post_path(p) %></p>
			<br>
		</li>
		<% end %>
	</ul>
	<% end %>
<%else %>
	<h3><%=@user.username%> Post(s)</h3>
	<% if @user.posts.count == 0 %>
		<h2>It looks like this user hasn't posted anything yet</h2>
	<% else %>
	<ul>
	<% @user.posts.each do |p| %>
		<li>Category: <%= link_to p.category.name, category_path(p.category) %>
			<br>
			<p>Title: <%= link_to p.title, post_path(p) %></p>
			<br>
		</li>
		<% end %>
	</ul>
	<% end %>
<% end %>


<br>
<br>
</div>
</div>